### ISSUE TITLE
[Feature] Update any API usernames to eng@

### ISSUE THREAD

**Issue by ashtine** [Rebuild-Black-Business/RBB-Website#287]
## User Story
As a user 
I want to call an API for eng
So I can be targeted in my audience

## Acceptance Criteria
- [ ] not sure what to put here

## Describe the solution you'd like
Update any API usernames to eng@

**Comment by magnificode** [comment]
@llexical wanted to bounce this one off you, are there places in the app (frontend or backend) where we're not using the `engineering@` email address for? Either in the code or in our registration with those APIs

**Comment by llexical** [comment]
@magnificode @ashtine I am honestly not sure what we want from this? Not even sure what "Update any API usernames to eng@" means.

(Also if we do user stories for non user specific stuff can we do "As a developer:" or "As a member of the business team" or whatever because its super confusing to read as though you are a user of the site :'))

**Comment by ashtine** [comment]
@llexical totally, I was taking a stab at it. This is a more technical implementation so whatever makes sense :)

**Comment by magnificode** [comment]
@llexical Yeah I think this is something that just was mentioned in a meeting at some point? I think that we can just use this ticket as a reminder to make sure that we remove any of our personal emails from features. I don't think there's too much of an actionable item here.

**Comment by magnificode** [comment]
Closing this issue, we'll re-open some more specific issues as they crop up.
